/**
 * @fileoverview Provides parsers for SVG documents and SVG path data.
 * This includes a full SVG parser that builds a hierarchical AST from the source,
 * and a specialized parser for the `d` attribute of SVG `<path>` elements.
 * Both parsers also provide methods for rendering the AST as syntax-highlighted HTML.
 */

import {Parser} from './parser.js'
import { createHandlerRegistry, AstNode } from '../utilities2/ast-manager.js'

/**
 * Creates a parser for SVG documents.
 * The parser first tokenizes the SVG source into a flat list of tags, comments, text, etc.
 * It then builds a hierarchical Abstract Syntax Tree (AST) from this flat list.
 * It provides methods for getting both the flat and hierarchical ASTs, and for
 * rendering them as syntax-highlighted HTML.
 * @returns {{
 *   astOf: function(string): object,
 *   flatAstOf: function(string): object,
 *   htmlOf: function(string): string,
 *   hierarchicalHtmlOf: function(string): string,
 *   pretty: function(object): string,
 *   prettyHierarchical: function(object): string,
 *   parseTag: function(string): object
 * }} An object with methods for parsing and rendering SVG.
 */
function SvgParser() {
  const parser = new Parser([{
      name: 'comment',
      pattern: /^<!--/,
      endPattern: /-->/
    }, // XML comments
    {
      name: 'doctype',
      pattern: /^<!DOCTYPE/,
      endPattern: />/i
    }, // DOCTYPE declaration
    {
      name: 'xmldecl',
      pattern: /^<\?xml/,
      endPattern: /\?>/i
    }, // XML declaration
    {
      name: 'cdata',
      pattern: /^<!\[CDATA\[/,
      endPattern: /\]\]>/
    }, // CDATA sections
    {
      name: 'tag',
      pattern: /^<\/?\w+[^>]*>/
    }, // Complete tags (both opening and closing)
    {
      name: 'text',
      pattern: /^[^<]+/
    }, // Text content between tags
    {
      name: 'whitespace',
      pattern: /^\s+/
    }, // Standalone whitespace
  ]);

  /**
   * Parses a tag string to extract its name, type, attributes, and whether it's self-closing.
   * @private
   * @param {string} tagString - The string representation of the tag (e.g., `<rect x="10">`).
   * @returns {{type: string, name: string, attributes: object, selfClosing: boolean}} An object containing the parsed tag information.
   */
  function parseTag(tagString) {
    const selfClosing = tagString.endsWith('/>');
    const closing = tagString.startsWith('</');

    if(closing) {
      const match = tagString.match(/^<\/(\w+)>/);
      return {
        type: 'closing',
        name: match ? match[1] : '',
        attributes: {},
        selfClosing: false
      };
    }

    // Extract tag name and attributes
    const match = tagString.match(/^<(\w+)([^>]*?)\/?>/);
    if(!match) {
      return {
        type: 'opening',
        name: 'unknown',
        attributes: {},
        selfClosing: selfClosing
      };
    }

    const tagName = match[1];
    const attrString = match[2];

    // Parse attributes
    const attributes = {};
    const attrRegex = /(\w+(?:-\w+)*)\s*=\s*["']([^"']*?)["']/g;
    let attrMatch;
    while((attrMatch = attrRegex.exec(attrString)) !== null) {
      attributes[attrMatch[1]] = attrMatch[2];
    }

    return {
      type: 'opening',
      name: tagName,
      attributes: attributes,
      selfClosing: selfClosing
    };
  }

  function safeString(str) {
    return str.replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function wrap(color, value) {
    return value ? '<span style="color:' + color + '">' + value + '</span>' :
      '';
  }

  function bwrap(color, value) {
    return value ? '<span style="background-color:' + color + '">' + value +
      '</span>' : '';
  }

  /**
   * Builds a hierarchical AST from a flat list of tokens.
   * This is the core logic for converting the token stream into a tree structure.
   * @private
   * @param {object} ast - The flat AST generated by the initial parser.
   * @returns {object} The root node of the hierarchical AST.
   */
  function buildHierarchy(ast) {
    const stack = [{
      token: 'root',
      subtree: [],
      value: null,
      jref: 0
    }];

    function processNode(node) {
      if(node.token === 'tag') {
        const tagInfo = parseTag(node.value || '');

        if(tagInfo.type === 'closing') {
          // Pop from stack until we find matching opening tag
          while(stack.length > 1) {
            const current = stack[stack.length - 1];
            if(current.tagName === tagInfo.name) {
              stack.pop();
              break;
            }
            stack.pop(); // Handle malformed HTML by popping unclosed tags
          }
        } else {
          // Opening tag
          const newNode = {
            token: tagInfo.name,
            subtree: [],
            value: node.value,
            jref: node.jref,
            tagName: tagInfo.name,
            attributes: tagInfo.attributes,
            selfClosing: tagInfo.selfClosing
          };

          stack[stack.length - 1].subtree.push(newNode);

          if(!tagInfo.selfClosing) {
            stack.push(newNode);
          }
        }
      } else if(node.token === 'text' && node.value && node.value.trim()) {
        // Only add non-empty text nodes
        stack[stack.length - 1].subtree.push({
          token: 'text',
          subtree: [],
          value: node.value,
          jref: node.jref
        });
      } else if(['comment', 'doctype', 'xmldecl', 'cdata'].includes(node
          .token)) {
        // Add special nodes as-is
        stack[stack.length - 1].subtree.push({
          token: node.token,
          subtree: [],
          value: node.value,
          jref: node.jref
        });
      }
    }

    // Process all nodes in the flat AST
    for(let node of ast.subtree) {
      processNode(node);
    }

    return stack[0];
  }

  /**
   * Renders a hierarchical AST to a syntax-highlighted HTML string.
   * @private
   * @param {object} ast - The root node of the hierarchical AST.
   * @returns {string} The generated HTML string.
   */
  function prettyHierarchical(ast) {
    let tok = ast.token;
    let val = safeString(ast.value || '');

    if(tok === 'comment') {
      return wrap('#3b3', val);
    }
    if(tok === 'doctype' || tok === 'xmldecl') {
      return wrap('#93f', val);
    }
    if(tok === 'cdata') {
      return wrap('#f93', val);
    }
    if(tok === 'text') {
      return safeString(val);
    }

    // Handle SVG elements with specific styling
    let result = '';

    if(tok === 'root') {
      // Root node - just render children
      for(let node of ast.subtree) {
        result += prettyHierarchical(node);
      }
      return result;
    }

    // SVG elements
    const svgShapes = ['rect', 'circle', 'ellipse', 'polygon', 'polyline',
      'path', 'line'
    ];
    const svgContainers = ['svg', 'g', 'defs', 'clipPath', 'mask'];
    const svgText = ['text', 'tspan'];

    let color = '#fff'; // default
    if(svgShapes.includes(tok)) {
      color = '#4fc3f7'; // light blue for shapes
    } else if(svgContainers.includes(tok)) {
      color = '#81c784'; // light green for containers
    } else if(svgText.includes(tok)) {
      color = '#ffb74d'; // orange for text
    } else if(tok === 'svg') {
      color = '#f06292'; // pink for root svg
    }

    // Render opening tag
    if(ast.selfClosing) {
      result += wrap(color, val);
    } else {
      // Extract tag name for opening/closing
      const openTag = val.replace(/\/>$/, '>');
      const closeTag = `</${tok}>`;

      result += wrap(color, openTag);

      // Render children
      for(let node of ast.subtree) {
        result += prettyHierarchical(node);
      }

      result += wrap(color, closeTag);
    }

    return result;
  }

  function pretty(ast) {
    let tok = ast.token;
    let val = safeString(ast.value || '');

    if(tok === 'comment') {
      return wrap('#3b3', val);
    }
    if(tok === 'doctype' || tok === 'xmldecl') {
      return wrap('#93f', val);
    }
    if(tok === 'cdata') {
      return wrap('#f93', val);
    }
    if(tok === 'tag') {
      const tagInfo = parseTag(ast.value || '');
      const svgShapes = ['rect', 'circle', 'ellipse', 'polygon', 'polyline',
        'path', 'line'
      ];
      const svgContainers = ['svg', 'g', 'defs', 'clipPath', 'mask'];

      let color = '#fff';
      if(svgShapes.includes(tagInfo.name)) {
        color = '#4fc3f7';
      } else if(svgContainers.includes(tagInfo.name)) {
        color = '#81c784';
      } else if(tagInfo.name === 'text') {
        color = '#ffb74d';
      }

      return wrap(color, val);
    }
    if(tok === 'text') {
      return val.trim() ? safeString(val) : wrap('#666', val);
    }
    if(tok === 'whitespace') {
      return bwrap('#333', val);
    }

    let result = '';
    for(let node of ast.subtree) {
      result += pretty(node);
    }
    return result || val;
  }

  return {
    astOf: (text) => {
      const flatAst = parser.parse(text);
      return buildHierarchy(flatAst);
    },
    flatAstOf: (text) => parser.parse(text),
    htmlOf: (text) => {
      let flatAst = parser.parse(text);
      return pretty(flatAst);
    },
    hierarchicalHtmlOf: (text) => {
      let ast = buildHierarchy(parser.parse(text));
      return prettyHierarchical(ast);
    },
    pretty: pretty,
    prettyHierarchical: prettyHierarchical,
    parseTag: parseTag
  };
}

/**
 * Creates a parser for SVG path data (the `d` attribute of `<path>` elements).
 * It tokenizes the path string into commands and numbers, and provides methods
 * to get an AST and render it as syntax-highlighted HTML.
 * @returns {{
 *   astOf: function(string): object,
 *   flatAstOf: function(string): object,
 *   htmlOf: function(string): string,
 *   pretty: function(object): string
 * }} An object with methods for parsing and rendering SVG path data.
 */
function SvgPathParser() {
  const parser = new Parser([{
      name: 'command',
      pattern: /^[MmLlHhVvCcSsQqTtAaZz]/
    }, // SVG path commands
    {
      name: 'number',
      pattern: /^-?\d*\.?\d+(?:[eE][+-]?\d+)?/
    }, // Numbers (including scientific notation)
    {
      name: 'comma',
      pattern: /^,/
    }, // Comma separators
    {
      name: 'whitespace',
      pattern: /^\s+/
    }, // Whitespace
  ]);

  function safeString(str) {
    return str.replace(/</g, '&lt;');
  }

  function wrap(color, value) {
    return value ? '<span style="color:' + color + '">' + value + '</span>' :
      '';
  }

  /**
   * Groups a flat list of path tokens into logical command groups.
   * For example, `['M', '10', '10']` becomes a single "pathCommand" node.
   * @private
   * @param {object} ast - The flat AST from the initial parse.
   * @returns {object} An AST where commands and their arguments are grouped.
   */
  function groupCommands(ast) {
    const groups = [];
    let currentGroup = null;

    for(let node of ast.subtree) {
      if(node.token === 'command') {
        if(currentGroup) {
          groups.push(currentGroup);
        }
        currentGroup = {
          token: 'pathCommand',
          subtree: [node],
          value: node.value,
          jref: node.jref,
          command: node.value
        };
      } else if(currentGroup && ['number', 'comma'].includes(node.token)) {
        currentGroup.subtree.push(node);
      }
    }

    if(currentGroup) {
      groups.push(currentGroup);
    }

    return {
      token: 'pathData',
      subtree: groups,
      value: null,
      jref: 0
    };
  }

  function pretty(ast) {
    let tok = ast.token;
    let val = safeString(ast.value || '');

    if(tok === 'command') {
      return wrap('#f93', val); // Orange for commands
    }
    if(tok === 'number') {
      return wrap('#3ef', val); // Blue for numbers
    }
    if(tok === 'comma') {
      return wrap('#666', val); // Gray for separators
    }
    if(tok === 'whitespace') {
      return val;
    }

    let result = '';
    for(let node of ast.subtree) {
      result += pretty(node);
    }
    return result || val;
  }

  return {
    astOf: (text) => {
      const flatAst = parser.parse(text);
      return groupCommands(flatAst);
    },
    flatAstOf: (text) => parser.parse(text),
    htmlOf: (text) => {
      let ast = parser.parse(text);
      return pretty(ast);
    },
    pretty: pretty
  };
}

// Create parser instances
const svgParser = SvgParser();
const svgPathParser = SvgPathParser();

// Example usage:

const svgCode = `
<?xml version="1.0" encoding="UTF-8"?>
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
  <!-- A simple rectangle -->
  <rect x="10" y="10" width="100" height="50" fill="blue" stroke="black" stroke-width="2"/>
  <circle cx="100" cy="100" r="30" fill="red"/>
  <text x="50" y="150">Hello SVG</text>
</svg>
`;

const pathData = "M10,10 L90,90 C100,100 120,120 150,150 Z";
/*

// Test the parsers
console.log("SVG AST:", JSON.stringify(svgParser.astOf(svgCode), null, 2));
console.log("SVG HTML:", svgParser.htmlOf(svgCode));
console.log("SVG Hierarchical HTML:", svgParser.hierarchicalHtmlOf(svgCode));

console.log("Path AST:", JSON.stringify(svgPathParser.astOf(pathData), null, 2));
console.log("Path HTML:", svgPathParser.htmlOf(pathData));
*/
// Integration with your AST classes:
const svgAst = createSvgAst(svgParser.astOf(svgCode));
/*
const rectangles = svgAst.findShapes('rect');
const allShapes = svgAst.findShapes();
console.log("Found rectangles:", rectangles.length);
console.log("Found shapes:", allShapes.length);
*/

// =================== USAGE EXAMPLES ===================

// Example usage with your existing parser:
//const jsParser = JsParser();
const code = `{ "rect": { "x": 10, "y": 20, "width": 100, "height": 50 } }`;
const parserOutput = jsProcessor.astOf(code);
const ast = createAst(parserOutput);

// Basic searching
const rectNodes = ast.findAll({
  token: 'string',
  value: '"rect"'
});
const firstRect = ast.find({
  token: 'string',
  value: '"rect"'
});

// Navigation
const children = ast.children;
const parent = firstRect.parent;
const nextSib = firstRect.nextSibling;

// SVG-specific example:
//const svgAst = createSvgAst(svgParserOutput);
const shapes = svgAst.findShapes();
const rectsInArea = svgAst.findInBounds(0, 0, 200, 200);
const centerShapes = svgAst.findByCoordinates(100, 100, 10);

// Add Mermaid end shapes to all rectangles
const rectangles = svgAst.findAll({
  token: 'rect'
});
rectangles.forEach(rect => rect.addMermaidEndShapes());

// Auto-generated exports
if (typeof window !== 'undefined') window.SvgParser = SvgParser;
export { SvgParser };
if (typeof window !== 'undefined') window.SvgPathParser = SvgPathParser;
export { SvgPathParser };
if (typeof window !== 'undefined') window.allShapes = allShapes;
export { allShapes };
if (typeof window !== 'undefined') window.ast = ast;
export { ast };
if (typeof window !== 'undefined') window.centerShapes = centerShapes;
export { centerShapes };
if (typeof window !== 'undefined') window.children = children;
export { children };
if (typeof window !== 'undefined') window.code = code;
export { code };
if (typeof window !== 'undefined') window.firstRect = firstRect;
export { firstRect };
if (typeof window !== 'undefined') window.nextSib = nextSib;
export { nextSib };
if (typeof window !== 'undefined') window.parent = parent;
export { parent };
if (typeof window !== 'undefined') window.parserOutput = parserOutput;
export { parserOutput };
if (typeof window !== 'undefined') window.pathData = pathData;
export { pathData };
if (typeof window !== 'undefined') window.rectNodes = rectNodes;
export { rectNodes };
if (typeof window !== 'undefined') window.rectangles = rectangles;
export { rectangles };
if (typeof window !== 'undefined') window.rectsInArea = rectsInArea;
export { rectsInArea };
if (typeof window !== 'undefined') window.shapes = shapes;
export { shapes };
if (typeof window !== 'undefined') window.svgAst = svgAst;
export { svgAst };
if (typeof window !== 'undefined') window.svgCode = svgCode;
export { svgCode };
if (typeof window !== 'undefined') window.svgParser = svgParser;
export { svgParser };
if (typeof window !== 'undefined') window.svgPathParser = svgPathParser;
export { svgPathParser };
